### ISSUE TITLE
 Incompatibility with combustion heaters from Sky Resources mod

### ISSUE THREAD

**Issue by Umbraminf** [Furgl/AutoPickup#6]
(I'm using 1.10.2 version)
[This](https://minecraft.curseforge.com/projects/sky-resources) mod adds a multiblock structure in which the player shoud drop some itens [inside an structure](http://i.imgur.com/W82n7Cr.gif) ,   I dropped the items but when i put the last block the items always come to my hand as if I had broke a block, I tried to remove Auto Pickup and it doesn't happen anymore, but I was wondering me if you and Bartz24 couldn't make an addon, I don't know, so it won't happen?

**Comment by Umbraminf** [comment]
By the way, YOUR MODS RULES!

**Comment by Furgl** [comment]
Unfortunately because of how the mod/Minecraft works, I can't prevent this from happening directly: whenever you click a block, nearby items are picked up in order to get items that are produced from clicking blocks, like music discs produced from clicking on jukeboxes. 

However, I did add a keybind to disable automatically picking up items in v2.5 that you can use to bypass this: 
[AutoPickup-1.10.2-2.5.jar.zip](https://github.com/Furgl/AutoPickup/files/1197924/AutoPickup-1.10.2-2.5.jar.zip)
Just hold down the keybind while placing the last block and items won't be picked up anymore. 

And I'm glad you're enjoying the mod!

**Comment by Umbraminf** [comment]
Thanks a lot, you realy helped me!
